{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.shafaat73",
    "module": "android-crop-kit",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-crop-kit-1.0.0.aar",
          "url": "android-crop-kit-1.0.0.aar",
          "size": 199126,
          "sha512": "49870a845aaebfc9946608f01588d05cf1a23fb337210085f028d319129519c2a737a95daebe7ddc24f52e05e36c6728014e348de9261cf95e3167e3b25b36d6",
          "sha256": "d5860a59f95d71271d8a2dfb62ce2edfba0594677f1225c157de3cc39c2379e3",
          "sha1": "a8c58bb3f49dbc94cf8e701b4c634b815eee1c93",
          "md5": "a835492581922985ebd4afc5e3c8fd08"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-crop-kit-1.0.0.aar",
          "url": "android-crop-kit-1.0.0.aar",
          "size": 199126,
          "sha512": "49870a845aaebfc9946608f01588d05cf1a23fb337210085f028d319129519c2a737a95daebe7ddc24f52e05e36c6728014e348de9261cf95e3167e3b25b36d6",
          "sha256": "d5860a59f95d71271d8a2dfb62ce2edfba0594677f1225c157de3cc39c2379e3",
          "sha1": "a8c58bb3f49dbc94cf8e701b4c634b815eee1c93",
          "md5": "a835492581922985ebd4afc5e3c8fd08"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "android-crop-kit-1.0.0-sources.jar",
          "url": "android-crop-kit-1.0.0-sources.jar",
          "size": 184176,
          "sha512": "5b768a68e4694ea2d3b16f34e60c14f38baa5dd7209a0354483881036e8837a370fee0a710e8c2b8f130af4184c55cca1fe4e0d04fdede36974b92e3397a780f",
          "sha256": "3dde8b410e4bf7c9876d0b664c7666a7d224a639cf7c98e0ffa2896aa9f0021a",
          "sha1": "96b7c16d5748ab96ecc3993be75bf772245de08c",
          "md5": "0f1bba76bd8903fd531ed417238aca2a"
        }
      ]
    }
  ]
}
