name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew :cropper:assembleRelease

      - name: Publish to Maven Central
        run: |
          ./gradlew publishAllPublicationsToMavenCentralRepository \
            -PmavenCentralUsername="${{ secrets.SONATYPE_NEXUS_USERNAME }}" \
            -PmavenCentralPassword="${{ secrets.SONATYPE_NEXUS_PASSWORD }}" \
            -PsigningInMemoryKey="${{ secrets.SIGNING_PRIVATE_KEY }}" \
            -PsigningInMemoryPassword="${{ secrets.SIGNING_PASSWORD }}" \
            -PsigningInMemoryKeyId="F154B26F"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cropper/build/outputs/aar/*.aar
            cropper/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
